#!/bin/bash

INITIAL_VERSION_NUM=${1}
MODIFIED_VERSION_NUM=${2}

MODIFIED_MAJOR_VERSION=$(ci-extractVersion major ${MODIFIED_VERSION_NUM}) || exit 1
MODIFIED_MINOR_VERSION=$(ci-extractVersion minor ${MODIFIED_VERSION_NUM}) || exit 1
INITIAL_MAJOR_VERSION=$(ci-extractVersion major ${INITIAL_VERSION_NUM}) || exit 1
INITIAL_MINOR_VERSION=$(ci-extractVersion minor ${INITIAL_VERSION_NUM}) || exit 1


if [[ "${INITIAL_MAJOR_VERSION}" -eq "${MODIFIED_MAJOR_VERSION}" ]] ; then
  if [[ "${INITIAL_MINOR_VERSION}" -eq "${MODIFIED_MINOR_VERSION}" ]] ; then
    exit 0
  fi
fi

if [[ "${INITIAL_MAJOR_VERSION}" -eq "${MODIFIED_MAJOR_VERSION}" ]] ; then
  if [[ "${INITIAL_MINOR_VERSION}" -lt "${MODIFIED_MINOR_VERSION}" ]] ; then
    exit 0
  fi
fi

if [[ "${INITIAL_MAJOR_VERSION}" -lt "${MODIFIED_MAJOR_VERSION}" ]] ; then
  exit 0
fi

echo "The version is not properly incremented" >&2
exit 1
