#!/bin/bash

TYPE=$1
VERSION=$2

if [[ $VERSION =~ ^([0-9]+)\.([0-9]+)$ ]] ; then
  MAJOR_VERSION=${BASH_REMATCH[1]}
  MINOR_VERSION=${BASH_REMATCH[2]}
  if [[  $TYPE = minor ]] ; then
    echo "${MINOR_VERSION}"
  else
    echo "${MAJOR_VERSION}"
  fi
else
  echo "Could not understand the version string" >&2
  exit 1
fi
