name: Repository Dispatch Build

on:
  repository_dispatch:
env:
  IMAGE_NAME: springbootimage

jobs: 
  repository-dispatch-build:
    name: Repository Dispatch Build
    runs-on: ubuntu-18.04

    steps:
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - uses: actions/checkout@v1

      - name: Checkout triggered sha
        run: git checkout -f "${{  github.event.client_payload.buildSha }}"
    
      - name: Get Release Version
        id: compute-release-version
        uses: ZeroWasteTeam/actions/compute-version@master
        with:
          build-branch: ${{ github.event.client_payload.buildBranch }}
         
      - name: mvn Build
        run: mvn build
          
      - name: Unit Test
        run: mvn test
        
      - name: Build image
        run: docker build . --file Dockerfile --tag image

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Docker Publish
        run: |       
          REPOSITORY_NAME_IN_SMALL=$(echo "$GITHUB_REPOSITORY" | tr '[:upper:]' '[:lower:]')
          IMAGE_ID=docker.pkg.github.com/$REPOSITORY_NAME_IN_SMALL/$IMAGE_NAME
          echo IMAGE_ID=${IMAGE_ID}
          echo VERSION=${{ steps.compute-release-version.outputs.version}}
          docker tag image $IMAGE_ID:${{ steps.compute-release-version.outputs.version}}
          docker push $IMAGE_ID:${{ steps.compute-release-version.outputs.version}}
