# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Pull Request Build

on:
  pull_request:
    branches:
      - 'master'
      - 'rel-*'

jobs:
  build:
    name: PR Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Validating versioning
      uses: ZeroWasteTeam/actions/verify-pr-version@master
      with:
        base-branch:  ${{ github.base_ref }} 
        merged-ref: ${{ github.sha }} 
     
           
    - name: PR - mvn Build
      run: mvn build
    - name: PR - mvn Test
      run: mvn test
